refactor: drop @types/cheerio
iconify/tools pull request #36
Opened 2023-11-18 03:27 UTC by yunsii

#35

2023-11-18 03:36 UTC, yunsii commented
Export default cheerio instance is deprecated, ref: https://github.com/cheeriojs/cheerio/blob/v1.0.0-rc.12/src/index.ts#L64

So importing `* as cheerio` instead of this default export, ref: https://github.com/cheeriojs/cheerio/blob/a13961b99f11fd260e6594f995ad86759347eddb/src/index.ts#L70 (newest code for now)

2023-11-24 08:21 UTC, cyberalien commented
Tested, it fails to compile pretty much on every change.

Are you not getting any errors when trying to build it?

2023-11-24 08:25 UTC, cyberalien requested changes

2023-11-24 09:52 UTC, yunsii commented
I only run build and test of @iconify/tools, I will process it right now.

2023-11-24 10:00 UTC, yunsii commented
@cyberalien It's wired, why encounter these errors?
![image](https://github.com/iconify/tools/assets/18096089/1aafe0a1-1f6d-4763-a697-f684b622c5a6)

2023-11-24 10:02 UTC, cyberalien commented
> I only run build and test of @iconify/tools, I will process it right now.

Yes, I'm running that too, other packages don't really matter. It doesn't work for me. 

> @cyberalien It's wired, why encounter these errors? ![image](https://user-images.githubusercontent.com/18096089/285423500-1aafe0a1-1f6d-4763-a697-f684b622c5a6.png)

This means dependencies weren't installed. Re-run `pnpm install` (or `ni` if you are using `@antfu/ni` package).

2023-11-24 10:03 UTC, cyberalien commented
> I only run build and test of @iconify/tools, I will process it right now.

Yes, I'm running that too, other packages don't really matter. It doesn't work for me. 

I'm getting errors when parsing types on every changed file.

2023-11-24 10:16 UTC, yunsii commented
> I'm getting errors when parsing types on every changed file.

What's the meaning? 
![image](https://github.com/iconify/tools/assets/18096089/bf04b36c-c6a4-465c-8617-5073baa1aea8)

Build passed, test encounters download errors only.

2023-11-24 10:17 UTC, cyberalien commented
Strange. Do you get errors when running lint command?

2023-11-24 10:18 UTC, yunsii commented
> Strange. Do you get errors when running lint command?

![image](https://github.com/iconify/tools/assets/18096089/2c07cbfe-975a-4790-acf6-ac83d7d8f8ab)

It seems alse not.

2023-11-24 10:25 UTC, cyberalien commented
This is what I get with build, with lint and you can also see a warning in editor

![Screenshot 2023-11-24 at 12 24 45](https://github.com/iconify/tools/assets/822287/32b268a3-f85d-406d-acca-4f4871989029)
![Screenshot 2023-11-24 at 12 24 37](https://github.com/iconify/tools/assets/822287/b855ed13-d647-4111-83d0-8ef522f43872)

2023-11-24 10:31 UTC, cyberalien commented
This is a very weird situation, not sure which dev environment is bugged: maybe yours, maybe mine. So currently running ci to test on separate environment.

2023-11-24 10:33 UTC, cyberalien commented
So ci run was a success, which means bug is in my environment. Very very weird.

Doh. Sorry.

2023-11-24 10:43 UTC, yunsii commented
I think you can use a online IDE to test, it works in my personal and company computer.

2023-11-24 10:45 UTC, cyberalien commented
Got it to work!

It appears pnpm left `@types/cheerio` in modules, even though packages no longer have it.

Doing some tests now...

2023-11-24 10:53 UTC, cyberalien commented
Works perfectly

2023-11-24 11:03 UTC, merged

2023-11-24 11:05 UTC, cyberalien commented
Thanks a lot and sorry for mess.

Merged. I've also removed duplicate entries, so types are now in one file.

2023-11-24 11:29 UTC, cyberalien commented
Published with `next` tag.

For now it won't be added to stable because:
- This is likely a breaking change, so at least new minor version is needed, not patch.
- I've ran into unrelated issue when working with large icons, which will more likely require another breaking change to fix, but that one will be a major change.

So this is a possibly breaking change and I will likely add another breaking change soon, so I'd rather have one new major version with all those changes instead of publishing temporary version.

2023-11-24 12:00 UTC, yunsii commented
Sure, @types/cheerio's types declare in global namespace 😂

2024-01-08 09:24 UTC, Jeet-Metapercept commented
is this fixed? we're still experiencing the same issue on 4.0.0

```
> tsc -b src/@iconify && node src/@iconify/build-icons.js

../../../common/temp/node_modules/.pnpm/@iconify+tools@4.0.0/node_modules/@iconify/tools/lib/misc/cheerio.d.ts:7:30 - error TS2315: Type 'Cheerio' is not generic.

7 type WrappedCheerioElement = cheerio.Cheerio<cheerio.Element>;
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../../common/temp/node_modules/.pnpm/@iconify+tools@4.0.0/node_modules/@iconify/tools/lib/svg/analyse/types.d.ts:56:38 - error TS2312: An interface can only extend an object type or intersection of object types with statically known members.

56 interface ExtendedTagElement extends CheerioElement, ExtendedTagElementUses, ExtendedTagElementRelations {
                                        ~~~~~~~~~~~~~~


Found 2 errors.
```